#!/bin/sh
# ─── Admin key check ─────────────────────────────────────────────────────────────
# Compares the admin key in .env.local against the key generated by the backend.
# Run after a fresh volume wipe (which rotates the key):
#   docker compose exec backend sh /scripts/check_admin_key.sh
#
# The backend's generate_key binary uses a random component, so the key changes
# on every call to generate_admin_key.sh. This script generates a key and compares
# it to CONVEX_SELF_HOSTED_ADMIN_KEY in .env.local. Because the key is random,
# a mismatch is expected after a fresh start — update .env.local with the printed
# key and re-run.
#
# Set PLUTUS_ADMIN_KEY_CHECK_WARN_ONLY=1 to only warn without failing.

set -e

CREDENTIALS_DIR="/convex/data/credentials"
INSTANCE_SECRET_FILE="${CREDENTIALS_DIR}/instance_secret"
ADMIN_KEY_STORE="${CREDENTIALS_DIR}/admin_key"

if [ ! -f "$INSTANCE_SECRET_FILE" ]; then
  echo "⚠  No instance_secret file found at $INSTANCE_SECRET_FILE"
  echo "   The backend may not have finished initializing yet."
  exit 0
fi

# Generate a fresh admin key. The generate_key binary is non-deterministic
# (uses OS randomness via getrandom), so each call produces a different key.
# We generate once and use it for this check only.
CURRENT_KEY=$(bash /convex/generate_admin_key.sh 2>/dev/null | tail -1 | tr -d '[:space:]')

if [ -z "$CURRENT_KEY" ]; then
  echo "⚠  Could not generate admin key."
  exit 0
fi

# Store it for the check script's own reference (won't match future generations).
echo "$CURRENT_KEY" > "$ADMIN_KEY_STORE" 2>/dev/null || true

# Read the expected key from .env.local on the host.
EXPECTED_KEY=""
if [ -f /app/.env.local ]; then
  EXPECTED_KEY=$(grep '^CONVEX_SELF_HOSTED_ADMIN_KEY=' /app/.env.local 2>/dev/null | sed 's/.*=//;s/^"//;s/"$//')
fi

if [ -z "$EXPECTED_KEY" ]; then
  echo "ℹ  No CONVEX_SELF_HOSTED_ADMIN_KEY found in /app/.env.local."
  echo "   Generate one with: docker compose exec backend ./generate_admin_key.sh"
  echo "   Then add it to .env.local and run: npx convex dev --once"
  echo "   (This is not an error — deploy continues.)"
  exit 0
fi

if [ "$CURRENT_KEY" = "$EXPECTED_KEY" ]; then
  echo "✓ Admin key matches (.env.local ✓)"
  echo "  Key: ${CURRENT_KEY%%|*}|..."
  exit 0
fi

echo "⚠  Admin key mismatch!"
echo "   Run this to get the current key:"
echo "     docker compose exec backend ./generate_admin_key.sh"
echo ""
echo "   Then update .env.local:"
echo "     CONVEX_SELF_HOSTED_ADMIN_KEY='${CURRENT_KEY}'"
echo ""
echo "   Then re-push and seed:"
echo "     npx convex dev --once"
echo "     npm run db:seed"
echo ""

if [ "${PLUTUS_ADMIN_KEY_CHECK_WARN_ONLY}" = "1" ]; then
  echo "   (PLUTUS_ADMIN_KEY_CHECK_WARN_ONLY=1 — only warning, deploy continues)"
else
  echo "   PLUTUS_ADMIN_KEY_CHECK_WARN_ONLY is not set — exiting 1 to block deploy."
  exit 1
fi
